apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: docker.io/risniking/k8s-cj-test
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
